### ISSUE TITLE
奨学金発表会

### ISSUE THREAD

**Issue by Anna-Oura** [kikuchiken-waseda/OuraAnna#100]
# 今までの進捗
- https://github.com/kikuchiken-waseda/OuraAnna/issues/92
- https://github.com/kikuchiken-waseda/OuraAnna/issues/94
# todo
- [x] 資料を訂正. 
- [x] 練習. 
- [x] 本番. 
- [x] コメントをまとめる.

**Comment by Anna-Oura** [comment]
# 訂正点
## 全体を通して
- [ ] 全体を見直す. 
  - 資料を何も見ていない状態で, 言いたいことを箇条書きで書く. 
  - そこだけのスライドで発表練習. 
  - 適宜スライドを追加する. 
  - 上の作業を繰り返す. 最終調整. 
- [ ] 大学院の話を端折りすぎているので, わかりやすくまとめる. 
  - 全体像(背景)
  - 卒業研究ではその中でも特にどこに注目したのか
  - 卒研の結果
  - では, 修士以降ではどこまで問題意識を広げるのか
  - どういう検討が必要になると考えられるか
- [ ] 自信あり気に話す. 
  - 自分の発表を録音して聞いてみると良い. 
## 細かいところ
- [ ] オプティカルフローの結果, 青い方が緑より目立っている. 
- [ ] また, 舌根は青い部分にはならない (ノイズではない) のでは？
- [ ] オプティカルフローの先行研究例と結果例が違いすぎててよく分からない. 
- [ ] 「実習」て言葉使わない. 
- [ ] アプローチのスライド要らない. 
- [ ] 特徴点を用いた輪郭 → 硬口蓋を前提とした調音空間 などの言い換え. 
- [ ] 「IPAが示す情報」という表現を訂正する. 
- [ ] IPAの補足スライド作る. 
- [ ] 「個人差は必要な情報では？(正規化処理によって必要な差を無くしてしまっていない？)」という質問が来ても答えられるように.

**Comment by Anna-Oura** [comment]
# 「発表の内容」訂正点
- [ ] 卒業研究の話をサッと書いて, 修士以降の研究は「まとめ」に書く. 
  - 「システムを目指す → 特に卒研では, 〜〜という点が, 〜〜という理由で重要なので, ここに取り組む → 修士以降では, 〜〜のために, 〜〜をやる. 」みたいな. 
- [ ] A4ピッタリ埋める.

**Comment by Anna-Oura** [comment]
# 伝えたい情報
- 音声による発話訓練では困難が生じる場合があるため, 調音運動を提示すると良い. ただ, 調音運動を提示するだけでもダメ, ちゃんとしたシステムの構築が必要. 
- 調音運動提示を用いた発話訓練の理想的な形態 : ユーザに調音運動方法を画像で提示 → ユーザがそれを真似て発音 → ユーザの音声を解析して調音運動を推定 → モデルとなっている調音方法とユーザの調音を比較 → 比較結果を提示 → 比較結果を元にユーザが発音 → ユーザの音声を解析して ...以下エンドレス
- ここで課題となる点は, 1 提示すべき調音画像って何？, 2 音響情報から調音運動ってどう推定するの？, 3 推定したモデルとの比較ってどうやるの？, 4 表示方法は？, などが挙げられる. 
- 卒業研究ではこの課題の中でも特に, 「提示すべき調音動画に関する検討」を行う. 
- 先行研究調査の結果, 既存の調音運動提示方法としては, ATR CALL 発音チャレンジが挙げられる. ただ, これはCGによる提示のため, 模式的な調音運動である. 
- 人間は人により骨格・器官など大きく異なる. そのため, 同じ音でも違う調音運動が必要. CGだと, 訓練すべき運動とは別の運動がなされうる可能性. 
- そこで, 私の卒業研究では, 実際の調音運動を撮像したrtMRIを用いた発話訓練のための調音運動呈示方法の検討を行う. 
- この目標を達成する上で, まず課題となるのは正規化処理. というのは先述の通り, 人によって調音は異なるため, その複数ある調音運動パタンの中でも特にどれを提示すべきかの検討が必要. 
- この検討のためには, そもそも「どのような調音運動パタンがあるのか」を見たい. そこで, 調音器官の枠組みを異なる被験者でも揃え, 資料を比較できるようにする処理を行った. 
- 主成分分析を用いた検討の結果, 先行研究手法と比較して特に硬口蓋付近における正規化に成功. 
- 次に, どこが運動しているのかを確認できるようにしたい, という課題. 
- オプティカルフローを用いて, 調音点の違いを画像から確認できるようになった. 
- ただ, ノイズが多い. フレーム間比較やノイズ除去も行ったが, 今のところ改善は見られないので, 平均化フィルタで何とかしようって考えには限界があるかも. ここは卒業研究における今後の課題. 
- まとめ. 卒業研究では発話訓練のための調音運動呈示方法の検討を行った. 結果, 正規化では先行研究手法よりも誤差が少ない結果が, 強調表示によって調音点が確認できる結果が得られた. 
- 卒業研究までには, 先述したとおり, 強調表示の精度改善が課題. 表示方法の変更などを考えている. 
- 修士以降の研究としては, 最初に説明した課題の中では別の部分になる「音響情報から調音運動を推定する方法」について取り組むつもり.

**Comment by Anna-Oura** [comment]
- 人間科学的な意義は？どのような情報を扱うの？
  - 「発話訓練に必要な情報は調音運動の中でもどこ？」という情報を扱う. その情報を踏まえた上で強調画像化する.
  - 意義は「発話訓練に必要な情報を提示できるようにすること」つまり「聴覚情報を用いなくても発話訓練ができるようになること」

**Comment by Anna-Oura** [comment]
# 頂いたコメント
- CGの方がわかりやすいと思うけど, 実際の資料を使った理由や意図があれば教えて欲しい. 
  - ( ATR CALL 発音チャレンジ という既存のシステムがあるとの補足スライドを見せながら, ) CG だと分かりやすいが, 実際の運動とは異なるという可能性がある. そこで, 私はまず実際の調音運動を撮像した rtMRI 資料を使った検討を行っている. 
  - 想定質問だったので何とかなったけど, 説明が若干下手だったな. 
- これは調音に詳しい方に向けたもの？それとも一般に向けたもの？
  - 一般に向けたものです. それに向けてオプティカルフローなどを使っています. 
- 正規化処理のアルゴリズムを教えて欲しい. それは大浦さん特有の手法というか, 研究のオリジナリティの一部なの？
  - 歯茎から背骨にかけてのラインを合わせることを目標に, 画像内の任意のオブジェクトを検出することで分析を行っております. 
  - 説明途中に質問してくださった先生が納得いただいたようで, 途中で終わった. もし続けば, 先行研究との比較や個人差をある程度残すことの意義に関して説明する予定だった. 
- オプティカルフローの検証方法はどうするの？
  - 以前別の発表でもご指摘いただき, 例えば調音に詳しくない方を対象としたアンケート方法などを考えていますが, まだ検討中の段階です. 
- 大学院だと逆推定課題に取り組むということだけど, それは全く卒研とは別のものとして取り組むってこと？
  - 一応その予定ですが, 全く別というものでもないつもりでいます. 最終的には卒研の結果と修士の結果を両方とも取り入れたシステムの構築を目指しています. 
- 最終的には聴覚障害者さんに向けたシステムとするの？
  - その予定ですが, 聴覚障害者に限らず健聴者も使えるシステムとしたいです. 
- (英語の先生から) 私は舌の位置などを指示して教えるので, こういうアプローチもあるんだなってとても新鮮さを感じた. 
  - ありがとうございます.

**Comment by Anna-Oura** [comment]
# まとめ
## よかった点
- 何となく, 研究内容自体は先生方に好印象そうだった. 
- 質問は想定したものが多かったため, 比較的迷うことはなかった. 
- 資料・発表はわかりやすいとコメント頂けた. 
- 質問は先生の聞きたい点を確認した上で, そこだけを簡潔に説明したつもり. 
## 反省点
- オプティカルフローの検証方法に関する考察が必要. 
## その他 感想
- 私含め9人だったが, 全員激強かった. 
- 目標に対する結果の考察をもう少し詳しくやっても良いかも. 
- 学際性や人間科学部である意義についてあまり私は触れてなかった, と感じた. 特に質問来なかったけど.

**Comment by Anna-Oura** [comment]
# 学振・DC2に関して
- 研究の位置付けが分からないと厳しい. 
  - 読み手にわかりやすい記述を. 
  - どういう人が審査しているのかを考える. 
  - 最近採択された課題はどんなもの？確認する. 
- 業績が少ないと厳しい. 研究できるかが分からない.
  - データ分析方法わかってます！て感じを出す. 
  - 計画はちゃんと考えてます！て感じを出す.  
- 読みにくいとダメ. 
  - 1ヶ月ぐらいに書き上げて, デザインの調整をする.

**Comment by Anna-Oura** [comment]
- 見たい動きが見れる＝IPAの表示
- オプティカルフロー自体どう？って問題もちょっと最近感じてる. 
- どう見えたらOKってのがまだ決まってない. 支援に特化した見え方？
- ビジブルスピーチ等だと「わかるようになる」って評価方法だったと思う. そういう評価方法をしようとするとどうなる？って話を考えられれば良かったかも. 
  - 聴覚支援において, どうやったら「わかった？」ってなる？という視点をおいて調べると良いかも.
