### ISSUE TITLE
卒論を書いて仮提出する. 

### ISSUE THREAD

**Issue by Anna-Oura** [kikuchiken-waseda/OuraAnna#113]
# 今までの進捗
- https://github.com/kikuchiken-waseda/OuraAnna/issues/106
- https://github.com/kikuchiken-waseda/OuraAnna/issues/109
# todo
 - [x] 目次案書き直し. 
- [x] 発表練習をしてみる. 
- [x] 適宜訂正. 
- [x] texに落とす. 
- [x] 肉付け. 
- [x] 最終確認. 
- [x] 提出. (12/5まで)

**Comment by Anna-Oura** [comment]
# 目次案
## はじめに
- 背景
  - 調音提示手法の需要. 
    - 日常生活を送る上で不便を感じず音声コミュニケーションを行いたい需要がある. 
    - 現状の発話訓練は音声による手法が一般的だが, 聴覚フィードバックができない場合はこの手法だと困難が生じる. 
    - そこで, 調音方法を提示する (視覚情報を用いて発話方法を提示する) 手法で解決が可能と推測される. 
  - 既存の手法の課題
    - 既存の調音運動提示を用いた発話訓練手法では模式図よる提示がある. 
      - 図：既存の手法の画面. 各音素で1つの調音運動パタンしか表示できていない, かつ各調音器官をどの方向に動かせば良いのかが分かりにくい. 
      - <img width="319" alt="ATRCALL" src="https://user-images.githubusercontent.com/61837100/144183344-8f0aa90e-3c4d-4fac-a388-28d7b9165953.png">
    -  実際の調音運動は人により異なる運動が必要になるため, 模式図では学習効率が下がる (学習者が訓練すべき運動とは異なる運動の提示がなされうる) 可能性が示唆される. 
    - そこで, 実際の調音運動資料を用いた提示方法の検討が必要であることが示唆される. 
  - 実際の調音運動資料を発話訓練に使う上での課題
    - 顔の大きさと傾きは発話者により異なるので, 無加工の状態では資料の比較はできない. 
    - 調音に詳しくない方では, 調音運動を提示してもどの調音運動に注目すれば良いかを確認できない. 
- 目標
  - 学習者が調音運動資料の何処に注目すれば良いのかを確認できるようにする. 
    - [x] 図：目標の概略. 調音運動資料に画像処理を施すことで, 学習者は何処に注目すれば良いか, また音素ごとで動きがどう異なるのかを理解することが可能となる. 
    - ![mokuhyou](https://user-images.githubusercontent.com/61837100/144184363-3e436795-5e7f-4218-bd98-5830813e7a67.png)
- 波及効果
  - 調音運動提示を用いた発話訓練システムの提案に役立つ. 
    - [x] 図：システムの概略図. 本研究成果は, 図内の左端の「調音運動資料の提示」場面で役立つと考えられる. 
    - ![saisyu_mokuhyou](https://user-images.githubusercontent.com/61837100/144185555-a1ec4234-4188-4204-b4de-892219a219cf.png)
  - 実際の調音運動資料を用いることで, CGでは実現が難しかったUI整備の向上を目指せる. 
## アプローチ
- 使用データ
  - real-time MRI資料を用いる. 
  - 日本語音素を発音しているもの. 
  - 正規化処理は /a/ を発話中の画像を対象に. 
## 正規化処理
- 目的
  - 発話訓練のためには, 同じ音でもどれだけ異なる調音運動があるのかを比較できるようにしたい. 
  - しかし, 人により顔の大きさ, 背骨の傾きは異なるため, 生のデータでは比較は不可能.
    - [x] 図：調音器官の個人差の比較. 生のデータでは顔の大きさや背骨の傾きに発話者ごとで差が生じている. 
    - ![seikika](https://user-images.githubusercontent.com/61837100/144186115-825677ba-d38f-433a-8e7b-471713aa3029.png)
  - そこで, 顔の傾きと大きさを揃える処理が必要. 
  - 先行研究手法では前鼻棘を基準とした正規化が行われている. 
  - ただ, 前鼻棘を揃えても硬口蓋の厚さ・形状は正規化できない (縦軸方向における正規化に弱い) .  
    - [x] 図：先行研究手法. 前棘鼻を基準とした正規化が行われている. 2つ目の図から, 硬口蓋ラインの正規化はまだできていないことを観察できる. 
    - <img width="338" alt="pre_seikika" src="https://user-images.githubusercontent.com/61837100/144187155-20186a0d-7312-4da1-8e75-eb23996edb18.png"><img width="431" alt="pre_seikika2" src="https://user-images.githubusercontent.com/61837100/144187776-9b6a1ae6-1b48-4ef8-bab5-e517b212ea34.png">
  - そこで,硬口蓋ラインを含めた正規化を目標とした. 
- 手法
  - 主成分分析を用いて, 回転・拡大縮小をMRIに施す処理を行なった. 
    - [x] 図：主成分分析手法. 任意のオブジェクトを対象に主成分を検出し, その傾きと大きさを一致させるために, MRIに回転・拡大縮小処理をかける. 
    - ![pca](https://user-images.githubusercontent.com/61837100/144186871-043477cd-b9f3-4db3-adf8-e4cdeb54f6f9.png)
  - 3つの特徴点のズレを縦軸・横軸方向それぞれで標準偏差として算出した. 
    - [x] 図：3つの特徴点. 硬口蓋のズレをLeftで, 背骨のズレをRightで確認可能. 
    - ![seikika_kensyou](https://user-images.githubusercontent.com/61837100/144188254-7e9ba253-3f55-4c72-b6b6-e4a1f021ceed.png)
- 結果
  - オブジェクトでの比較. 
    - 顔輪郭, 口腔輪郭, 硬口蓋を基準とした特徴点を用いた口腔空間の3つで比較. 
      - [x] 図：使用した3つのオブジェクト. 
      - ![pca_kao](https://user-images.githubusercontent.com/61837100/144188455-1d931073-9cb0-40f0-9fb5-2b46a41cf95b.png)<img width="141" alt="pca_koukuu" src="https://user-images.githubusercontent.com/61837100/144188464-2e98b16a-7640-4ea9-9762-d02525b47ba9.png">![pca_koukuu_tokutyou](https://user-images.githubusercontent.com/61837100/144188472-e27f5a81-44ae-4d26-ab15-912b7fe8e3b3.png)
      - [x] 表：標準偏差の結果
  - 先行研究での比較. 
    - 提案手法(特徴点を用いた口腔空間)と, 既存の手法を比較. 
      - [x] 図：先行研究手法との比較
      - ![pca_senkou](https://user-images.githubusercontent.com/61837100/144188685-8d739998-ca00-46f3-a8db-f04e88fe2f3b.png)<img width="165" alt="pca_teian" src="https://user-images.githubusercontent.com/61837100/144188694-ac778bb5-feea-4198-9a38-9ede4b1f87e7.png">
      - [x] 表：標準偏差の結果
- 考察
  - オブジェクトの比較からは, 特徴点を用いた口腔空間の結果が最も良かった. 
  - そこで, 最も精度が良かった口腔空間を用いた提案手法と先行研究を再現した手法を比較したところ, 縦軸方向における誤差が少ない結果が得られた. 
  - 以上より, 先行研究手法と比較して, 主成分分析を用いることで硬口蓋ラインの正規化が可能になったと考えられる. 
## 強調表示処理
- 目的
  - 学習者が, 調音運動資料を見て重要な運動がどれかを確認できることが目標.  
    - [x] 表：IPA. 音ごとにどのような調音運動をするのかを提示している情報. 重要な調音運動を提示している情報の1つである. 
    - <img width="297" alt="ipa_vo" src="https://user-images.githubusercontent.com/61837100/144189518-64af5fa9-9824-430a-8036-b3f44419a242.png"><img width="701" alt="ipa_con" src="https://user-images.githubusercontent.com/61837100/144189524-a870a751-df25-421f-a4a8-f7c9028ed029.png">
- 手法
  - 運動の検出が可能なオプティカルフロー法を用いて検討を行なった. 
  - オプティカルフローを用いた先行研究としては, 読唇のために唇付近の運動を分析した研究がある. 
    - [ ] 図：先行研究
  - MRIは読唇とは異なり頭部全体を撮影したものである上に, 身体の内部を撮像したもののため, 調音とは関係のない部位の運動やノイズによる誤検知された運動が検知される可能性が考えられる. 
  - そこで, ノイズ除去とフレーム間を変更する処理も行った. 
- 結果
  - 正規化処理済みのMRIにオプティカルフロー処理をかけた. 
    - [x] 表：未処理の状態のMRIオプティカルフロー結果
    - ![opt_demo](https://user-images.githubusercontent.com/61837100/144195067-8ac4b0f4-4a17-421e-89fd-529b195d98bf.png)
  - バイラテラル処理を用いた. 
    - [x] 表：バイラテラル処理前と処理後の比較. 
    - ![opt_noise](https://user-images.githubusercontent.com/61837100/144195095-f187f60c-6155-4bc3-80f0-b662587af254.png)
  - フレーム間を変更した. 
      - [x] 表：1フレーム結果と2フレーム結果の比較. 
      - ![opt_frame](https://user-images.githubusercontent.com/61837100/144195086-9960e0da-f539-4aa3-80a8-8f161be57ae2.png)
  - 舌を対象とした窓を設定し, その領域内のベクトルの平均値を算出した. 
      - [ ] 表：変更前後の比較. 
  - (今後書き足す部分)
- 考察
  - 未処理の状態では, 背骨など調音とは関係のない部分にも線が多く引かれる. 
  - ノイズ除去やフレーム間変更などを施したが, 重要な調音運動のわかりやすさはあまり変わらない. 
  - ROIを定義して一部の運動に限って結果を観察することで, 運動を確認しやすくなった. ただ, 平均値では外れ値の影響を考慮できない. 
  - そこで, (今後書き足す部分)
## まとめ
- まとめ
  - 本研究では, rtMRIを発話訓練に用いるための手法を検討した. 
  - 正規化処理では先行研究手法と比較して, 硬口蓋付近における誤差が少ない結果が, 強調表示では任意の領域における運動
  - 以上より本研究では, 発話者ごとに, 音ごとの調音運動の違いを rtMRI 資料から比較できる成果が得られた. 
    - [ ] 図：結果の概略. RAWデータと編集済みデータを並べる. RAWデータと比較して, 
- 今後の展望
  - 最終的には, 実用場面で使える発話訓練システムの開発に取り組みたい. 
  - 本研究では,  「調音運動を提示するために, どの運動が重要になるか」を表示できるようになった, という段階. 
  - 今後は, ユーザの声を分析して的確なフィードバックを返せるようにするために, 音響情報から調音運動を推定する手法の検討に取り組む. 
## 参考文献
## アペンディクス
- 正規化処理. オブジェクトの自動検出. 
  - セマンティックセグメンテーションを用いてオブジェクトの検出を行なった. 
  - 23枚の画像で機械学習を行った結果, 概ね良好な結果が得られた. 
  - ただ, 手動で検出したものと誤差を比較したところ, まだ自動化手法の方が誤差が多いことが見られた. 
  - 学習データを増やすことで, より精度が向上することが考えられる. 
- 任意領域の抽出. カスケード分類器. 
  - 舌を検出するカスケード分類器を作成した. 
  - ...枚で機械学習を行った結果, 概ね良好な結果が得られた. 
  - これは, 最終的に発話訓練システムを作成する際に, 確認したい点のみ表示するなどの機能作成に役立つと考えられる. 
- セントロイドの検出. 
  - 唇におけるセントロイドの検出を行なった. 
  - 円唇している方が非円唇よりもセントロイドが唇の前側に来ていることが分かったが, 結果の差は微量であった. 
  - これは円唇・非円唇の検出に役立つと考えられるが, 現状では差が微量なため, 発話訓練に応用するためにはより検討が必要である. 
## 謝辞

**Comment by Anna-Oura** [comment]
目次案：https://github.com/kikuchiken-waseda/OuraAnna/blob/master/b4-seminer/documents/%E5%8D%92%E8%AB%96%E6%9C%AC%E4%BD%93/%E7%9B%AE%E6%AC%A1%E6%A1%88.md

**Comment by Anna-Oura** [comment]
# 資料
- [本体pdf](https://github.com/kikuchiken-waseda/OuraAnna/blob/master/b4-seminer/documents/%E5%8D%92%E8%AB%96%E6%9C%AC%E4%BD%93/2021_1205_%E5%8D%92%E8%AB%96%EF%BC%88%E5%A4%A7%E6%B5%A6%EF%BC%89.pdf), [tex](https://github.com/kikuchiken-waseda/OuraAnna/blob/master/b4-seminer/documents/%E5%8D%92%E8%AB%96%E6%9C%AC%E4%BD%93/tex.md)
- [要旨pdf](https://github.com/kikuchiken-waseda/OuraAnna/blob/master/b4-seminer/documents/%E5%8D%92%E8%AB%96%E8%A6%81%E6%97%A8/2021_1205_%E8%A6%81%E6%97%A8%EF%BC%88%E5%A4%A7%E6%B5%A6%EF%BC%89.pdf)

**Comment by Anna-Oura** [comment]
2021/12/05提出.

**Comment by Anna-Oura** [comment]
# GM
- 方法, アプローチはもう書けると思うので, どんどん書いていこう. 
- 正規化処理の結果・考察も書く. 
- オプティカルフローは, まず目的と方法を整理し直す. まだカオスだと思う. 
- 目的が分離されたら, 大きな背景が書けるようになるはず. いきなり書き始めないでね. 
- 来週は, 大きい目的→小さい目的 の関係性が成り立っているかを確認する. 
  - 「美味しいカレー作る→美味しいスパイス作る」はOK. だけど, 「包丁の磨き方」とかは, まあ関係あるけど...みたいな印象ある. 
  - 小さい目的達成できたら, こういうことがわかりました. だから, 多く目的のうちコレが達成しました. コレが考察に値する. 
  - 各種の目的に対する考察をより綺麗にしていこう. それ以外のところはどんどん書いてって.

**Comment by Anna-Oura** [comment]
# GM 細かい指摘
- 1章の背景のところで, 「重要な運動を表示したい→そこでIPAというのがある」との内容を入れる. 
- 背景のところで, 「わかりやすい表示とは→最低限IPA」みたいなノリにすると良いと思う. 
- オプティカルフローの手法が目的になっていない？手法は「アルゴリズムは...計算は...」とか. 
- 「何をやったか」は考察ではなくまとめ. 考察は「結果がこうだった, だから...」てやつ, 結果からわかる情報のみ書く.

**Comment by Anna-Oura** [comment]
Last Change: 2021/12/03

# 目次案
## はじめに
- 背景
  - 調音提示手法の需要. 
    - 現状の発話訓練は音声による手法が一般的だが, 聴覚フィードバックができない場合はこの手法だと困難が生じる. 
    - そこで, 調音方法を提示する (視覚情報を用いて発話方法を提示する) 手法で解決が可能と推測される. 
  - 既存の手法の課題
    - 既存の調音運動提示を用いた発話訓練手法では模式図よる提示がある. 
      - 図：既存の手法の画面. 各音素で1つの調音運動パタンを表示している. 
      - <img width="319" alt="ATRCALL" src="https://user-images.githubusercontent.com/61837100/144183344-8f0aa90e-3c4d-4fac-a388-28d7b9165953.png">
    - 実際の調音運動は人により異なる運動が必要になるため, 模式図では学習効率が下がる (学習者が訓練すべき運動とは異なる運動の提示がなされうる) 可能性が示唆される. 
    - そこで, 実際の調音運動資料を用いた提示方法の検討が必要であることが示唆される. 
  - 実際の調音運動資料を発話訓練に使う上での課題
    - 顔の大きさと傾きは発話者により異なるので, 無加工の状態では資料の比較はできない. 
    - 調音に詳しくない方では, 調音運動を提示してもどの調音運動に注目すれば良いかを確認できない. 
- 目標
  - 学習者が調音運動資料の何処に注目すれば良いのか, かつ音素ごとで動きがどう異なるのかを確認できるようにする. 
    - [x] 図：目標の概略. 調音運動資料に画像処理を施すことで, 学習者は何処に注目すれば良いか, また音素ごとで動きがどう異なるのかを理解することが可能となる. 
    - <img width="491" alt="mokuhyou" src="https://user-images.githubusercontent.com/61837100/144520178-4aaffa45-c6d6-42dd-b1d8-f49569787c18.png">
- 波及効果
  - 調音運動提示を用いた発話訓練システムの提案に役立つ. 
    - [x] 図：システムの概略図. 本研究成果は, 図内の左端の「調音運動資料の提示」場面で役立つと考えられる. 
    - ![saisyu_mokuhyou](https://user-images.githubusercontent.com/61837100/144185555-a1ec4234-4188-4204-b4de-892219a219cf.png)
  - 実際の調音運動資料を用いることで, CGでは実現が難しかったUI整備の向上を目指せる. 
## アプローチ
- 使用データ
  - 実際の調音運動を撮像した real-time MRI 資料を用いる. 
  - 日本語の発話練習を想定し, 日本語音素を発音しているものを選択. 
- 本稿の構成
  - 「学習者が調音運動資料の何処に注目すれば良いのか」を解決するために, 正規化処理を行った. 
  - 「音素ごとで動きがどう異なるのか」を解決するために, 強調表示処理を行った. 
## 正規化処理
- 目的
  - 発話訓練のためには, 同じ音でもどれだけ異なる調音運動があるのかを比較できるようにしたい. 
  - しかし, 人により顔の大きさ, 背骨の傾きは異なるため, 生のデータでは比較は不可能.
    - [x] 図：調音器官の個人差の比較. 生のデータでは顔の大きさや背骨の傾きに発話者ごとで差が生じている. 
    - ![seikika](https://user-images.githubusercontent.com/61837100/144520216-c4a5fc57-d9b0-4b71-8060-923ee8edf433.png)
  - そこで, 顔の傾きと大きさを揃える処理が必要. 
  - 先行研究手法では前鼻棘を基準とした正規化が行われている. 
  - ただ, 前鼻棘を揃えても硬口蓋の厚さ・形状は正規化できない (縦軸方向における正規化に弱い) .  
    - [x] 図：先行研究手法. 前棘鼻を基準とした正規化が行われている. 2つ目の図から, 硬口蓋ラインの正規化はまだできていないことが観察できる. 
    - <img width="338" alt="pre_seikika" src="https://user-images.githubusercontent.com/61837100/144187155-20186a0d-7312-4da1-8e75-eb23996edb18.png"><img width="431" alt="pre_seikika2" src="https://user-images.githubusercontent.com/61837100/144187776-9b6a1ae6-1b48-4ef8-bab5-e517b212ea34.png">
  - そこで, 硬口蓋ラインを含めた正規化を目標とした. 
- 手法
  - 主成分分析を用いて, 回転・拡大縮小をMRIに施す処理を行なった. 
    - [x] 図：主成分分析手法. 任意のオブジェクトを対象に主成分を検出(A)し, その傾きと大きさを一致させるために, MRIに回転・拡大縮小処理(B)をかける. 
    - ![pca](https://user-images.githubusercontent.com/61837100/144520243-386affb3-b25f-436f-9778-5ee2f9734b24.png)
  - 3つの特徴点のズレを縦軸・横軸方向それぞれで標準偏差として算出した. 
    - [x] 図：3つの特徴点. ●をLeft, ■をUp, ▲をRightと表記する. 硬口蓋のズレをLeftで, 背骨のズレをRightで確認可能. 
    - <img src="https://user-images.githubusercontent.com/61837100/144520302-7a239ccd-5fda-4563-981b-cfe98359fccf.png" width="200">
- 結果
  - オブジェクトでの比較. 
    - 顔輪郭, 口腔輪郭, 硬口蓋を基準とした特徴点を用いた口腔空間の3つで比較. 
      - [x] 図：使用した3つのオブジェクト. 
      - ![pca_kao](https://user-images.githubusercontent.com/61837100/144188455-1d931073-9cb0-40f0-9fb5-2b46a41cf95b.png)<img width="141" alt="pca_koukuu" src="https://user-images.githubusercontent.com/61837100/144188464-2e98b16a-7640-4ea9-9762-d02525b47ba9.png">![pca_koukuu_tokutyou](https://user-images.githubusercontent.com/61837100/144188472-e27f5a81-44ae-4d26-ab15-912b7fe8e3b3.png)
      - [x] 表：標準偏差の結果
  - 先行研究での比較. 
    - 提案手法(特徴点を用いた口腔空間)と, 既存の手法を比較. 
      - [x] 表：標準偏差の結果
- 考察
  - オブジェクトの比較からは, 特徴点を用いた口腔空間の結果が最も良かった. これは, 特徴点を使うことで, 例えば顎付近の脂肪など調音とは関係のない個人差の考慮を防いでいるのでは. 
  - そこで, 最も精度が良かった口腔空間を用いた提案手法と先行研究を再現した手法を比較したところ, 縦軸方向における誤差が少ない結果が得られた. これは, 硬口蓋形状も含めた画像の分析を行うことで, 縦軸方向の正規化が可能になったと考えられる.
  - 以上より, 本研究の成果としては, 硬口蓋形状も含めた画像の正規化を可能とした点. 
## 強調表示処理
- 目的
  - 発話訓練のためには, 学習者が調音運動資料を見て重要な運動がどれかを判別できる必要がある.
  - RAWの調音運動資料では何処が重要なのかわからないので, 重要な運動を強調表示する必要がある. 
  - 重要な調音運動とは何処に当たるか. 
    - 重要な調音運動を扱っている1つとしては, IPAが挙げられる. 
      - [x] 表：IPA. 音ごとにどのような調音運動をするのかを提示している情報. 重要な調音運動を提示している情報の1つである. 
      - <img width="297" alt="ipa_vo" src="https://user-images.githubusercontent.com/61837100/144189518-64af5fa9-9824-430a-8036-b3f44419a242.png"><img width="701" alt="ipa_con" src="https://user-images.githubusercontent.com/61837100/144189524-a870a751-df25-421f-a4a8-f7c9028ed029.png">
  - そこで本研究では, IPAも注目している舌の運動に注目し, 運動の表示を目標に行った. 
- 手法
  - 運動の検出が可能なオプティカルフロー法を用いて検討を行なった. 
  - オプティカルフローを用いた先行研究としては, 読唇のために唇付近の運動を分析した研究がある. 
    - [ ] 図：先行研究
  - MRIは読唇とは異なり頭部全体を撮影したものである上に, 身体の内部を撮像したもののため, 調音とは関係のない部位の運動やノイズによる誤検知された運動が検知される可能性が考えられる. 
  - そこで, ノイズ除去やフレーム間を変更する処理, 一部領域に限って分析する処理などを行った. 
- 結果
  - 正規化処理済みのMRIにオプティカルフロー処理をかけた. 
    - [x] 表：未処理の状態のMRIオプティカルフロー結果
    - <img src="https://user-images.githubusercontent.com/61837100/144520479-ca9b9911-6a1b-45c5-a399-f56d9cdf62e0.png" width="400">
  - バイラテラル処理を用いた. 
    - [x] 表：バイラテラル処理前と処理後の比較. 
    - <img src="https://user-images.githubusercontent.com/61837100/144694114-89f0948a-ad09-4bb4-9d11-b2ba425097b3.png" width="400">
  - フレーム間を変更した. 
      - [x] 表：1フレーム結果と2フレーム結果の比較. 
      - <img src="https://user-images.githubusercontent.com/61837100/144694148-360ac9e7-3752-4903-9433-fbca1d428c9e.png" width="400">
  - 舌を対象とした窓を設定し, その領域内のベクトルの平均値を算出した. 
      - [x] 表：変更前後の比較. 
      - <img src="https://user-images.githubusercontent.com/61837100/144520512-5e9d2fcc-3edc-438c-b28b-72ae71d11f38.png" width="400">
  - (今後書き足す部分)
- 考察
  - 未処理の状態では, 背骨など調音とは関係のない部分にも線が多く引かれる. 
  - ノイズ除去やフレーム間変更などを施したが, 重要な調音運動のわかりやすさはあまり変わらない. 
  - ROIを定義して一部の運動に限って結果を観察することで, 運動を確認しやすくなった. ただ, 平均値では外れ値の影響を考慮できない. 
  - そこで, (今後書き足す部分)を行った結果, (今後書き足す部分)という結果が得られた. 
## まとめ
- まとめ
  - 本研究では, rtMRIを発話訓練に用いるための手法を検討した.「音素ごとで動きがどう異なるのか」を解決するためにを解決するために正規化処理を,「学習者が調音運動資料の何処に注目すれば良いのか」を解決するために強調表示処理を行った. 
  - 正規化処理では先行研究手法と比較して, 硬口蓋付近における誤差が少ない結果が, 強調表示では(今後書き足す部分)という結果が得られた.
    - [ ] 図：結果の概略. RAWデータと編集済みデータを並べる. RAWデータと比較して, (今後書き足す部分). 
  - 以上より本研究では, 発話者ごとに, 音ごとの調音運動の違いを rtMRI 資料から比較できる成果が得られたと言える. 
- 今後の展望
  - 最終的には, 実用場面で使える発話訓練システムの開発に取り組みたい. 
  - 本研究では, 「調音運動を提示するためにどの運動が重要になるか」を表示できるようになった, という段階. 
  - 今後は, ユーザの声を分析して的確なフィードバックを返せるようにするために, 音響情報から調音運動を推定する手法の検討に取り組む. 
## 参考文献
## アペンディクス
- 正規化処理. オブジェクトの自動検出. 
  - セマンティックセグメンテーションを用いてオブジェクトの検出を行なった. 
  - 23枚の画像で機械学習を行った結果, 概ね良好な結果が得られた. 
  - ただ, 手動で検出したものと誤差を比較したところ, まだ自動化手法の方が誤差が多いことが見られた. 
  - 学習データを増やすことで, より精度が向上することが考えられる. 
- 任意領域の抽出. カスケード分類器. 
  - 舌を検出するカスケード分類器を作成した. 
  - ...枚で機械学習を行った結果, 概ね良好な結果が得られた. 
  - これは, 最終的に発話訓練システムを作成する際に, 確認したい点のみ表示するなどの機能作成に役立つと考えられる. 
- セントロイドの検出. 
  - 唇におけるセントロイドの検出を行なった. 
  - 円唇している方が非円唇よりもセントロイドが唇の前側に来ていることが分かったが, 結果の差は微量であった. 
  - これは円唇・非円唇の検出に役立つと考えられるが, 現状では差が微量なため, 発話訓練に応用するためにはより検討が必要である. 
## 謝辞
